#!/usr/bin/env bash
# Transfers a file from client to a server

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i ~/.ssh/holberton "$1" ubuntu@34.73.190.173:~/
fi
