#!/usr/bin/env bash
# Create a custom 404 page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404code.html
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://google.com;" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server/a error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
service nginx start
