#!/usr/bin/env bash
# Create a custom 404 page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://google.com; error_page 404 /404.html" /etc/nginx/sites-available/default
service nginx start
