#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "frontend http_front
        bind *:80
        mode http
        default_backend http_back

backend http_back
        balance roundrobin
        server webserver1 34.73.190.173:80 check
        server webserver2 18.208.189.15:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
