#!/usr/bin/env bash
# This script displays "Hi" on the 9th iteration 
counter=1
while [ $counter -le 10 ]
do
    echo "Holberton School"

    if [ $counter == 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
